import {
  ABasic,
  AStroke,
  EBasic,
  EStroke,
  MBasic,
  MStroke,
  TBasic,
  TStroke,
  VBasic,
  VStroke,
} from "../assets/letters";

import {
  SliderImage1,
  SliderImage10,
  SliderImage11,
  SliderImage12,
  SliderImage13,
  SliderImage14,
  SliderImage15,
  SliderImage16,
  SliderImage17,
  SliderImage18,
  SliderImage19,
  // SliderImage2,
  SliderImage20,
  SliderImage21,
  SliderImage22,
  SliderImage23,
  SliderImage24,
  SliderImage25,
  SliderImage26,
  SliderImage27,
  SliderImage28,
  SliderImage29,
  SliderImage3,
  SliderImage30,
  SliderImage4,
  SliderImage5,
  SliderImage6,
  SliderImage7,
  SliderImage8,
  SliderImage9,
} from "../assets/img";

export const bigTitle = [
  { letter: "V", currentImage: 0, image: [VBasic, VStroke] },
  { letter: "E", currentImage: 0, image: [EBasic, EStroke] },
  { letter: "T", currentImage: 0, image: [TBasic, TStroke] },
  { letter: "M", currentImage: 0, image: [MBasic, MStroke] },
  { letter: "A", currentImage: 0, image: [ABasic, AStroke] },
];

export const slider1Images = [
  SliderImage1,
  SliderImage3,
  SliderImage4,
  SliderImage5,
  SliderImage6,
  SliderImage7,
  SliderImage8,
  SliderImage9,
  SliderImage10,
  SliderImage11,
  SliderImage12,
  SliderImage13,
  SliderImage14,
  SliderImage15,
];

export const slider2Images = [
  SliderImage16,
  SliderImage17,
  SliderImage18,
  SliderImage19,
  SliderImage20,
  SliderImage21,
  SliderImage22,
  SliderImage23,
  SliderImage24,
  SliderImage25,
  SliderImage26,
  SliderImage27,
  SliderImage28,
  SliderImage29,
  SliderImage30,
];
